[package]
name = "coasters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
bevy = "0.9.1"
bevy_flycam = "0.9.0"
iyes_loopless = "0.9.1"
pythagorean-hodographs = "0.4.0"
