[package]
name = "coasters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
bevy = "0.12.1"
bevy_flycam = "0.12.0"
pythagorean-hodographs = "0.5.3"
